VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "search" do |search|
	  search.vm.box = "ubuntu/precise64"
	  search.vm.hostname = "search.dev"
	  search.vm.provision :shell, path: "bootstrap.sh"
	  search.vm.network :private_network, ip:"192.168.44.44"
	  search.vm.network :forwarded_port, host: 9200, guest: 9200
	  search.vm.network :forwarded_port, host: 9300, guest: 9300
	  search.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
		v.name = "ElasticSearch-2.x"
      end
  end
end